spring.application.name=secure-banking-system
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/banking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Chakri@7799
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Security Settings
# (The secret key must be at least 256-bit / 32 characters long for HS256)
banking.app.jwtSecret=secretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKey
banking.app.jwtExpirationMs=86400000